import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { PlusCircle, Trash2, Sparkles, Loader2, ArrowLeft, X } from "lucide-react";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import { currencySymbols } from "../../utils/helper";
import toast from "react-hot-toast";

const CURRENCIES = ["USD", "EUR", "GBP", "INR", "CAD", "AUD"];
const STATUSES = ["PENDING", "DRAFT", "PAID"];

const emptyItem = { description: "", quantity: 1, unitPrice: 0 };

function CreateInvoice() {
  const navigate = useNavigate();
  const [saving, setSaving] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [draftLoading, setDraftLoading] = useState(false);
  const [showDraft, setShowDraft] = useState(false);
  const [draftText, setDraftText] = useState("");

  const [form, setForm] = useState({
    clientName: "",
    clientEmail: "",
    clientAddress: "",
    issueDate: new Date().toISOString().split("T")[0],
    dueDate: "",
    currency: "USD",
    taxRate: 0,
    discount: 0,
    shipping: 0,
    status: "PENDING",
    notes: "",
    items: [{ ...emptyItem }],
  });

  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const setItem = (index, key, value) =>
    setForm((f) => ({
      ...f,
      items: f.items.map((it, i) => (i === index ? { ...it, [key]: value } : it)),
    }));
  const addItem = () => setForm((f) => ({ ...f, items: [...f.items, { ...emptyItem }] }));
  const removeItem = (index) =>
    setForm((f) => ({
      ...f,
      items: f.items.length === 1 ? f.items : f.items.filter((_, i) => i !== index),
    }));

  const subtotal = form.items.reduce((s, it) => s + (it.quantity * it.unitPrice || 0), 0);
  const taxAmount = (subtotal * Number(form.taxRate || 0)) / 100;
  const discountAmount = Math.min(Number(form.discount || 0), subtotal);
  const total = subtotal + taxAmount - discountAmount + Number(form.shipping || 0);
  const symbol = currencySymbols[form.currency] || form.currency + " ";
  const money = (n) =>
    symbol + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const handleAiDescribe = async () => {
    const itemsToDescribe = form.items.map((it) => it.description).filter(Boolean);
    if (!itemsToDescribe.length) {
      toast.error("Add item descriptions first to use AI enhancement");
      return;
    }
    setAiLoading(true);
    try {
      const res = await axiosInstance.post(API_PATHS.ai.generate, {
        promptItems: itemsToDescribe,
      });
      const enhanced = res.data.items || [];
      setForm((f) => ({
        ...f,
        items: f.items.map((it, i) =>
          enhanced[i]
            ? {
                ...it,
                description: enhanced[i].description || it.description,
                quantity: enhanced[i].quantity || it.quantity,
                unitPrice: enhanced[i].unitPrice,
              }
            : it,
        ),
      }));
      toast.success("Items enhanced by AI");
    } catch (err) {
      toast.error(err.response?.data?.message || "AI enhancement failed");
    } finally {
      setAiLoading(false);
    }
  };

  const handleAIDraft = async () => {
    if (!draftText.trim()) {
      toast.error("Describe your invoice first");
      return;
    }
    setDraftLoading(true);
    try {
      const res = await axiosInstance.post(API_PATHS.ai.draft, {
        text: draftText,
        currency: form.currency,
      });
      const d = res.data.draft || {};
      setForm((f) => ({
        ...f,
        clientName: d.clientName || f.clientName,
        clientEmail: d.clientEmail || f.clientEmail,
        clientAddress: d.clientAddress || f.clientAddress,
        notes: d.notes || f.notes,
        items: (d.items && d.items.length ? d.items : f.items).map((it) => ({
          description: it.description,
          quantity: it.quantity,
          unitPrice: it.unitPrice,
        })),
      }));
      toast.success("Draft generated by AI");
    } catch (err) {
      toast.error(err.response?.data?.message || "AI draft failed");
    } finally {
      setDraftLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.items.some((it) => it.description.trim())) {
      toast.error("Add at least one item with a description");
      return;
    }
    setSaving(true);
    try {
      const payload = { ...form };
      await axiosInstance.post(API_PATHS.invoices.create, payload);
      toast.success("Invoice created");
      navigate("/invoices");
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to create invoice");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <Link
          to="/invoices"
          className="rounded-lg border border-gray-200 bg-white p-2 text-gray-500 transition-colors hover:bg-gray-50"
          aria-label="Back to invoices"
        >
          <ArrowLeft size={16} />
        </Link>
        <div>
          <h1 className="text-2xl font-bold">New invoice</h1>
          <p className="text-sm text-gray-500">Create a professional invoice in minutes.</p>
        </div>
      </div>

      <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
        <div className="mb-3 flex items-center gap-2">
          <Sparkles size={18} className="text-primary" />
          <h2 className="font-semibold">AI assistant</h2>
        </div>
        <p className="mb-3 text-sm text-gray-500">
          Describe your work in plain language and let AI draft the invoice for you.
        </p>
        <div className="flex flex-col gap-2 sm:flex-row">
          <textarea
            value={draftText}
            onChange={(e) => setDraftText(e.target.value)}
            placeholder='e.g. "Designed a landing page for Acme Corp, 3 pages, $500 each, plus 4 logo concepts at $150"'
            rows={2}
            className="flex-1 resize-none rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/20"
          />
          <button
            type="button"
            onClick={handleAIDraft}
            disabled={draftLoading}
            className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-primary/90 disabled:opacity-60"
          >
            {draftLoading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
            Generate draft
          </button>
        </div>
        {showDraft && (
          <button
            onClick={() => setShowDraft(false)}
            className="mt-2 text-xs text-gray-400 hover:underline"
          >
            Hide draft tip
          </button>
        )}
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid gap-6 lg:grid-cols-3">
          <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm lg:col-span-2">
            <h2 className="mb-4 font-semibold">Client details</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <label className="mb-1 block text-sm font-medium">Client name *</label>
                <input
                  required
                  value={form.clientName}
                  onChange={(e) => set("clientName", e.target.value)}
                  placeholder="Acme Corp"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Client email *</label>
                <input
                  required
                  type="email"
                  value={form.clientEmail}
                  onChange={(e) => set("clientEmail", e.target.value)}
                  placeholder="billing@acme.com"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div className="sm:col-span-2">
                <label className="mb-1 block text-sm font-medium">Client address</label>
                <input
                  value={form.clientAddress}
                  onChange={(e) => set("clientAddress", e.target.value)}
                  placeholder="123 Main St, City"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
            </div>
          </section>

          <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <h2 className="mb-4 font-semibold">Invoice settings</h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-1 block text-sm font-medium">Issue date</label>
                  <input
                    type="date"
                    value={form.issueDate}
                    onChange={(e) => set("issueDate", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Due date</label>
                  <input
                    type="date"
                    value={form.dueDate}
                    onChange={(e) => set("dueDate", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-1 block text-sm font-medium">Currency</label>
                  <select
                    value={form.currency}
                    onChange={(e) => set("currency", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  >
                    {CURRENCIES.map((c) => (
                      <option key={c} value={c}>
                        {c} ({currencySymbols[c]})
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Status</label>
                  <select
                    value={form.status}
                    onChange={(e) => set("status", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  >
                    {STATUSES.map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="mb-1 block text-sm font-medium">Tax %</label>
                  <input
                    type="number"
                    min="0"
                    value={form.taxRate}
                    onChange={(e) => set("taxRate", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Discount</label>
                  <input
                    type="number"
                    min="0"
                    value={form.discount}
                    onChange={(e) => set("discount", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Shipping</label>
                  <input
                    type="number"
                    min="0"
                    value={form.shipping}
                    onChange={(e) => set("shipping", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium">Notes</label>
                <textarea
                  value={form.notes}
                  onChange={(e) => set("notes", e.target.value)}
                  rows={2}
                  placeholder="Payment terms, thank you note, etc."
                  className="w-full resize-none rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                />
              </div>
            </div>
          </section>
        </div>

        <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
            <h2 className="font-semibold">Line items</h2>
            <button
              type="button"
              onClick={handleAiDescribe}
              disabled={aiLoading}
              className="inline-flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary transition-colors hover:bg-primary/10 disabled:opacity-60"
            >
              {aiLoading ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
              {aiLoading ? "Enhancing..." : "Enhance descriptions with AI"}
            </button>
          </div>

          <div className="space-y-3">
            {form.items.map((item, idx) => (
              <div key={idx} className="grid grid-cols-12 items-end gap-3">
                <div className="col-span-12 sm:col-span-6">
                  <label className="mb-1 block text-xs text-gray-400">Description</label>
                  <input
                    value={item.description}
                    onChange={(e) => setItem(idx, "description", e.target.value)}
                    placeholder="Service or product"
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div className="col-span-4 sm:col-span-2">
                  <label className="mb-1 block text-xs text-gray-400">Qty</label>
                  <input
                    type="number"
                    min="0"
                    value={item.quantity}
                    onChange={(e) => setItem(idx, "quantity", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div className="col-span-4 sm:col-span-3">
                  <label className="mb-1 block text-xs text-gray-400">Rate</label>
                  <input
                    type="number"
                    min="0"
                    value={item.unitPrice}
                    onChange={(e) => setItem(idx, "unitPrice", e.target.value)}
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-primary"
                  />
                </div>
                <div className="col-span-4 flex items-center justify-end gap-2 sm:col-span-1">
                  <span className="hidden text-sm font-semibold text-gray-600 sm:block">
                    {money((item.quantity || 0) * (item.unitPrice || 0))}
                  </span>
                  <button
                    type="button"
                    onClick={() => removeItem(idx)}
                    className="rounded-lg p-2 text-gray-400 transition-colors hover:bg-red-50 hover:text-red-500"
                    aria-label="Remove item"
                  >
                    <X size={16} />
                  </button>
                </div>
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={addItem}
            className="mt-4 inline-flex items-center gap-2 rounded-lg border border-dashed border-gray-300 px-4 py-2 text-sm font-medium text-gray-500 transition-colors hover:border-primary hover:text-primary"
          >
            <PlusCircle size={16} /> Add item
          </button>
        </section>

        <section className="ml-auto max-w-sm rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-gray-500">Subtotal</span>
              <span>{money(subtotal)}</span>
            </div>
            {discountAmount > 0 && (
              <div className="flex justify-between">
                <span className="text-gray-500">Discount</span>
                <span>-{money(discountAmount)}</span>
              </div>
            )}
            <div className="flex justify-between">
              <span className="text-gray-500">Tax ({form.taxRate}%)</span>
              <span>{money(taxAmount)}</span>
            </div>
            {Number(form.shipping) > 0 && (
              <div className="flex justify-between">
                <span className="text-gray-500">Shipping</span>
                <span>{money(Number(form.shipping))}</span>
              </div>
            )}
            <div className="flex justify-between border-t border-gray-200 pt-3 text-base font-bold">
              <span>Total</span>
              <span>{money(total)}</span>
            </div>
          </div>

          <button
            type="submit"
            disabled={saving}
            className="mt-5 w-full rounded-lg bg-primary py-2.5 text-sm font-semibold text-white transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {saving ? "Creating..." : "Create invoice"}
          </button>
        </section>
      </form>
    </div>
  );
}

export default CreateInvoice;
